import type { RssFeedPreset } from "./types";

const POLITICS_EXCLUDED_KEYWORDS = [
  "election",
  "campaign",
  "vote",
  "voting",
  "president",
  "prime minister",
  "minister",
  "parliament",
  "congress",
  "government",
  "cabinet",
  "war",
  "military",
  "sanction",
  "diplomacy",
  "geopolitics",
  "foreign policy",
  "protest",
  "coup",
  "regime",
  "invasion",
  "strike",
  "ceasefire",
  "territorial dispute",
  "alliance",
  "закон",
  "правительство",
  "президент",
  "министр",
  "парламент",
  "войн",
  "санкц",
  "дипломат",
  "выбор",
  "протест",
];

const DISTRESS_EXCLUDED_KEYWORDS = [
  "killed",
  "killing",
  "dead",
  "death",
  "fatal",
  "suicide",
  "murder",
  "crime",
  "attack",
  "bomb",
  "injured",
  "погиб",
  "погибли",
  "смерт",
  "суицид",
  "убий",
  "теракт",
];

const WORLD_EXCLUDED_KEYWORDS = [
  ...POLITICS_EXCLUDED_KEYWORDS,
  ...DISTRESS_EXCLUDED_KEYWORDS,
  "fifa",
  "world cup",
  "football",
  "soccer",
  "tournament",
  "match",
  "championship",
  "banknote",
  "currency",
  "exchange rate",
  "ruble",
  "dollar",
  "валют",
  "курс",
  "рубл",
  "доллар",
  "банкнот",
];

const AI_INCLUDED_KEYWORDS = [
  "AI",
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "LLM",
  "large language model",
  "language model",
  "foundation model",
  "generative",
  "neural",
  "inference",
  "training",
  "prompt",
  "agent",
  "robot",
  "Claude",
  "Llama",
  "OpenAI",
  "model",
  "модель",
  "нейросет",
  "искусственн",
  "машинн",
] as const;

const MARKETS_EXCLUDED_KEYWORDS = [
  ...POLITICS_EXCLUDED_KEYWORDS,
  "tariff",
  "trade war",
  "embargo",
];

const SPORTS_EXCLUDED_KEYWORDS = [
  ...POLITICS_EXCLUDED_KEYWORDS,
  ...DISTRESS_EXCLUDED_KEYWORDS,
  "died",
  "dead",
  "tragic",
  "трагед",
  "где смотреть",
  "трансляц",
  "онлайн",
];

export const MIRO_RSS_FEED_PRESETS = {
  scienceDailyTechnology: {
    url: "https://www.sciencedaily.com/rss/top/technology.xml",
    source: "ScienceDaily",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  nasaTechnology: {
    url: "https://www.nasa.gov/technology/feed/",
    source: "NASA Technology",
    category_hint: "Tech",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  openAiNews: {
    url: "https://openai.com/news/rss.xml",
    source: "OpenAI News",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  openAiDevelopers: {
    url: "https://developers.openai.com/rss.xml",
    source: "OpenAI Developers",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  googleDeepMind: {
    url: "https://deepmind.google/blog/rss.xml",
    source: "Google DeepMind",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  googleAiBlog: {
    url: "https://blog.google/technology/ai/rss/",
    source: "Google AI",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  googleResearch: {
    url: "https://research.google/blog/rss/",
    source: "Google Research",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
    includeKeywords: AI_INCLUDED_KEYWORDS,
  },
  amazonScience: {
    url: "https://www.amazon.science/index.rss",
    source: "Amazon Science",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
    includeKeywords: AI_INCLUDED_KEYWORDS,
    singleItem: true,
  },
  microsoftResearch: {
    url: "https://www.microsoft.com/en-us/research/feed/",
    source: "Microsoft Research",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
    includeKeywords: AI_INCLUDED_KEYWORDS,
    singleItem: true,
  },
  mitMachineLearning: {
    url: "https://news.mit.edu/rss/topic/machine-learning",
    source: "MIT Machine Learning",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
    includeKeywords: AI_INCLUDED_KEYWORDS,
    singleItem: true,
  },
  huggingFaceBlog: {
    url: "https://huggingface.co/blog/feed.xml",
    source: "Hugging Face Blog",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  microsoftAiBlog: {
    url: "https://blogs.microsoft.com/ai/feed/",
    source: "Microsoft AI Blog",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  habrAi: {
    url: "https://habr.com/ru/rss/hubs/artificial_intelligence/articles/?fl=ru",
    source: "Habr AI",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  physOrg: {
    url: "https://phys.org/rss-feed/",
    source: "Phys.org",
    category_hint: "World",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  nasaNewsReleases: {
    url: "https://www.nasa.gov/news-release/feed/",
    source: "NASA News Releases",
    category_hint: "World",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  esaSpaceScience: {
    url: "https://www.esa.int/rssfeed/Our_Activities/Space_Science",
    source: "ESA Space Science",
    category_hint: "World",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  habrDevelop: {
    url: "https://habr.com/ru/rss/flows/develop/",
    source: "Habr Develop",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  techCrunch: {
    url: "https://techcrunch.com/feed/",
    source: "TechCrunch",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  ixbtNews: {
    url: "https://www.ixbt.com/export/news.rss",
    source: "iXBT",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  threeDNews: {
    url: "https://3dnews.ru/news/rss/",
    source: "3DNews",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  arsTechnica: {
    url: "https://feeds.arstechnica.com/arstechnica/index",
    source: "Ars Technica",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  onlinerTech: {
    url: "https://tech.onliner.by/feed",
    source: "Onliner Tech",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  onlinerPeople: {
    url: "https://people.onliner.by/feed",
    source: "Onliner People",
    category_hint: "World",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  onlinerMoney: {
    url: "https://money.onliner.by/feed",
    source: "Onliner Money",
    category_hint: "World",
    excludedKeywords: MARKETS_EXCLUDED_KEYWORDS,
  },
  nplus1: {
    url: "https://nplus1.ru/rss",
    source: "N+1",
    category_hint: "World",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  devBy: {
    url: "https://devby.io/rss",
    source: "Dev.by",
    category_hint: "Tech",
    excludedKeywords: POLITICS_EXCLUDED_KEYWORDS,
  },
  officeLife: {
    url: "https://officelife.media/rss/",
    source: "Office Life",
    category_hint: "Markets",
    excludedKeywords: MARKETS_EXCLUDED_KEYWORDS,
  },
  nakedScience: {
    url: "https://naked-science.ru/feed",
    source: "Naked Science",
    category_hint: "World",
    excludedKeywords: WORLD_EXCLUDED_KEYWORDS,
  },
  bloombergMarkets: {
    url: "https://feeds.bloomberg.com/markets/news.rss",
    source: "Bloomberg Markets",
    category_hint: "Markets",
    excludedKeywords: MARKETS_EXCLUDED_KEYWORDS,
  },
  coinDesk: {
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    source: "CoinDesk",
    category_hint: "Markets",
    excludedKeywords: MARKETS_EXCLUDED_KEYWORDS,
  },
  sportsRu: {
    url: "https://www.sports.ru/rss/all_news.xml",
    source: "Sports.ru",
    category_hint: "Sports",
    excludedKeywords: SPORTS_EXCLUDED_KEYWORDS,
  },
  mlbNews: {
    url: "https://www.mlb.com/feeds/news/rss.xml",
    source: "MLB News",
    category_hint: "Sports",
    excludedKeywords: SPORTS_EXCLUDED_KEYWORDS,
  },
  sportExpress: {
    url: "https://www.sport-express.ru/services/materials/news/se/",
    source: "Sport-Express",
    category_hint: "Sports",
    excludedKeywords: SPORTS_EXCLUDED_KEYWORDS,
  },
  pressball: {
    url: "https://pressball.by/feed/",
    source: "Pressball",
    category_hint: "Sports",
    excludedKeywords: SPORTS_EXCLUDED_KEYWORDS,
  },
} satisfies Record<string, RssFeedPreset>;
